# Programming Assignment 5

## 0. Preliminaries

Import numpy and matplotlib.pyplot with the usual aliases.

In [ ]:
# Write your code here

## 1. Array creation

Write NumPy commands that create the following arrays.

<details>
    <summary>Hint</summary>
For arrays containing sequential numbers, use a combination of arange or linspace, np.newaxis, reshape, and transpose.
</details>

---
a.
```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```

---
b.
```
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
```

---
c.
```
[[[3 3]
  [3 3]]

 [[3 3]
  [3 3]]]
```

---
d.
```
[[10]
 [11]
 [12]
 [13]]
```

---
e.
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```

---
f.
```
[[1 4 7]
 [2 5 8]
 [3 6 9]]
```

In [ ]:
# Write your code here
# Use code comments to identify the sub-part letter for each line

## 2. Array manipulation

This task builds familiarity with creating, manipulating, and visualizing numpy arrays.

1. Create a 1-D array named `x` with 200 points covering the range 0 to 4π
3. Compute $y = 10\sin(4x) + x$
4. Plot `x` and `y`
6. Create a copy of y named `y_pos`
5. Create an array named `idx` which is `True` where `y_pos<0`.
7. Set the negative values of `y_pos` to zero. Now all values of `y_pos` should be ≥0.
8. Plot `x` and `y_pos`


In [ ]:
# Write your code here

## 3. 2-D Array manipulation 

1. Create 1-D arrays named `x` and `y` representing cartesian coordinates. `x` should contain 200 values in the range [0,20]. `y` should contain 100 values in the range [0,6].
2. Use meshgrid to create 2-D arrays of `xx` and `yy`. These represent the cartesian x and y coordinates at each location in the 100 x 200 grid.
3. Calculate the quantity $f = 10 + 2\sin(x) + y$. (`f` should be 2-D and have the same shape as `xx` and `yy`.)
4. Visualize `f` on the x-y plane using pcolormesh
5. Compute the mean and standard deviation of `f` over the entire domain. Using a print statement, format the values as follows, with 3 decimal places for each number:
```
   mean: x.xxx
    std: x.xxx
```

In [ ]:
# Write your code here

## 4. Gridded data analysis

In this task, you will analyze gridded atmospheric data. The data are mean air temperature at 2 m above ground level (T2m) for July 2024, as estimated by the NASA MERRA-2 reanalysis. MERRA-2 has a resolution of 0.5° latitude and 0.625° longitude, so T2m is a 2-D array with has hundreds of data points in each dimension. You will visualize the data and compute zonal and meridional means.

The data files for this assignment are in the prog5_files subfolder in `.npy` format. (We will use NetCDF files later in the course.)

1. Load data from the files in the prog5_files folder: T2m.npy, lat.npy, lon.npy. Use `T2m`, `lat`, and `lon` as the names of variables that you read from these files. 
2. How many longitudes are there in the dataset? How many latitudes? Is the shape of T2m (latitude,longitude) or (longitude,latitude)?  Write your answers in code comments. 
3. Check the mean value of `T2m` and explain in code comments why the temperature is likely in kelvin units.
4. Convert T2m from kelvin to Celsius.
5. Visualize the temperature (now in Celsius) using `pcolormesh`. (You can probably identify some geographic features even though we haven't plotted coastlines.) Add a colorbar.
6. Average the temperature across latitudes (meridional mean) using `T2m.mean(axis=...)`. This will create a 1-D array with the same shape as `lon`. Plot the meridional mean temperature as a function of longitude (line plot).
7. Average the temperature across longitudes (zonal mean). This will create a 1-D array with the same shape as `lat`. Plot the zonal mean temperature as a function of latitude (line plot).
8. What latitude (approximately) has the warmest mean temperature? 

In [ ]:
# Write your code here
# You will need additional code cells for each plot.

# Load latitude data (provided as example)
lat = np.load('prog5_files/lat.npy')